# Generated by Django 2.2 on 2020-02-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsinfo',
            name='band_type',
            field=models.CharField(default='', help_text='类型', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='cellsinfo',
            name='sector',
            field=models.CharField(default='', help_text='扇区', max_length=20, verbose_name='扇区'),
        ),
        migrations.AlterField(
            model_name='cellsinfo',
            name='sector_code',
            field=models.CharField(default='', help_text='扇区code', max_length=20, verbose_name='扇区code'),
        ),
    ]
