# Generated by Django 2.2 on 2020-02-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecels', '0002_auto_20200220_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellsinfo',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='cellsinfo',
            name='common_site_code',
        ),
        migrations.RemoveField(
            model_name='cellsinfo',
            name='dist_code',
        ),
        migrations.RemoveField(
            model_name='cellsinfo',
            name='sector_code',
        ),
        migrations.RemoveField(
            model_name='cellslevel',
            name='code',
        ),
    ]
