# Generated by Django 2.2 on 2020-02-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecels', '0002_auto_20200223_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellslevel',
            options={'verbose_name': '共站树 ', 'verbose_name_plural': '共站树 '},
        ),
    ]
