# Generated by Django 2.2 on 2020-02-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecels', '0003_auto_20200220_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellsinfo',
            name='sector',
            field=models.CharField(default='', help_text='扇区', max_length=50, verbose_name='扇区'),
        ),
    ]
