# Generated by Django 2.2 on 2020-02-28 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecels', '0003_auto_20200223_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellsGui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(default='', help_text='小区名', max_length=50, verbose_name='小区名')),
                ('polygon_info', models.TextField(default='', help_text='多边形顶点', verbose_name='多边形顶点')),
                ('color', models.CharField(default='', help_text='颜色', max_length=10, verbose_name='颜色')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_level', models.ForeignKey(blank=True, help_text='父级别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_gui', to='ecels.CellsInfo', verbose_name='父级别')),
            ],
            options={
                'verbose_name': '小区界面描述',
                'verbose_name_plural': '小区界面描述',
            },
        ),
    ]
