# Generated by Django 2.2 on 2020-02-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecels', '0004_auto_20200220_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CellsInfo',
        ),
    ]
