# Generated by Django 2.2 on 2020-02-20 23:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecels', '0005_delete_cellsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist', models.CharField(default='', help_text='地市', max_length=10, verbose_name='地市')),
                ('city', models.CharField(default='', help_text='区县', max_length=10, verbose_name='区县')),
                ('site_name', models.CharField(default='', help_text='基站名', max_length=50, verbose_name='基站名')),
                ('cell_name', models.CharField(default='', help_text='小区名', max_length=50, verbose_name='小区名')),
                ('site_id', models.CharField(default='', help_text='站号', max_length=20, verbose_name='站号')),
                ('enbid', models.CharField(default='', help_text='eNBID', max_length=20, verbose_name='eNBID')),
                ('local_cell_id', models.CharField(default='', help_text='本地小区ID', max_length=20, verbose_name='本地小区ID')),
                ('eci', models.CharField(default='', help_text='ECI', max_length=20, verbose_name='ECI')),
                ('physical_cell_id', models.CharField(default='', help_text='物理小区标识', max_length=20, verbose_name='物理小区标识')),
                ('pci_mod3', models.CharField(default='', help_text='PCIMOD3', max_length=20, verbose_name='PCIMOD3')),
                ('tac', models.CharField(default='', help_text='跟踪区', max_length=20, verbose_name='跟踪区')),
                ('longitude', models.CharField(default='', help_text='经度', max_length=20, verbose_name='经度')),
                ('latitude', models.CharField(default='', help_text='纬度', max_length=20, verbose_name='纬度')),
                ('frequency_band', models.CharField(default='', help_text='频段', max_length=20, verbose_name='频段')),
                ('frequency_point', models.CharField(default='', help_text='频点号', max_length=20, verbose_name='频点号')),
                ('bandwidth', models.CharField(default='', help_text='带宽', max_length=20, verbose_name='带宽')),
                ('site_type', models.CharField(default='', help_text='站型', max_length=20, verbose_name='站型')),
                ('azimuth', models.CharField(default='', help_text='方位角', max_length=20, verbose_name='方位角')),
                ('station_height', models.CharField(default='', help_text='站高', max_length=20, verbose_name='站高')),
                ('total_pitch_angle', models.CharField(default='', help_text='总俯仰角', max_length=20, verbose_name='总俯仰角')),
                ('inner_pitch_angle', models.CharField(default='', help_text='内置下倾角', max_length=20, verbose_name='内置下倾角')),
                ('electronic_pitch_angle', models.CharField(default='', help_text='电下倾角', max_length=20, verbose_name='电下倾角')),
                ('mechanical_pitch_angle', models.CharField(default='', help_text='机械下倾角', max_length=20, verbose_name='机械下倾角')),
                ('sprod_name', models.CharField(default='', help_text='厂家', max_length=20, verbose_name='厂家')),
                ('grid_info', models.CharField(default='', help_text='网格信息', max_length=50, verbose_name='网格信息')),
                ('band_type', models.CharField(default='', help_text='类型', max_length=20, verbose_name='类型')),
                ('common_site_name', models.CharField(default='', help_text='共站名', max_length=50, verbose_name='共站名')),
                ('sector', models.CharField(default='', help_text='扇区', max_length=50, verbose_name='扇区')),
                ('desc', models.TextField(default='', help_text='描述', verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_level', models.ForeignKey(blank=True, help_text='父级别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cells', to='ecels.CellsLevel', verbose_name='父级别')),
            ],
            options={
                'verbose_name': '工参信息',
                'verbose_name_plural': '工参信息',
            },
        ),
    ]
