# Generated by Django 2.2 on 2020-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(help_text='电话号码', max_length=11, verbose_name='电话'),
        ),
    ]
